# Generated by Django 4.1.7 on 2023-02-16 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_customer_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('view_history', 'can view history')]},
        ),
    ]
